### ISSUE TITLE
fisherman breaks after updating fish

### ISSUE THREAD

**Issue by gyakovlev** [fisherman/homebrew-tap#1]
Fisherman formula links to a version dependent directories:

`/usr/local/Cellar/fish/<version>/share/fish/vendor_functions.d
 /usr/local/Cellar/fish/<version>/share/fish/vendor_completions.d`
 and if fish version gets upgraded it no longer loads fisherman.

**Comment by brj** [comment]
Sorry about that. That's a problem with the tap then. 

Please uninstall, then install again using the recommended method in the project's README. 

I think I will blow up this repo and the brew install method with it when I get a chance.

**Comment by gyakovlev** [comment]
I'm not sure if It's an issue with a tap of formula, or how homebrew creates symlinks. I can do some research but it'll take some time.

**Comment by brj** [comment]
Thanks @gyakovlev!

**Comment by gyakovlev** [comment]
ok, did quick research. it's kind of complicated issue and involves all parties =)

depends on this https://github.com/fish-shell/fish-shell/pull/2896
it's included and released as of fish 2.3.0
but the homebrew formula does not take advantage of extra_completionsdir etc...

here is homebrew's issue https://github.com/Homebrew/legacy-homebrew/issues/45124

after fixing homebrew this tap should be able to use version-independant directory to place function code and completion code.

will try to poke homebrew people about the issue

**Comment by gyakovlev** [comment]
https://github.com/Homebrew/homebrew-core/pull/2813/files

this fixes the issue, waiting Homebrew to accept my PR.

also fisherman formula becomes significantly simpler
I'll create PR for this repo after Homebrew accepts the fix.

```
class Fisherman < Formula
    desc "fish plugin manager"
    homepage "https://github.com/fisherman/fisherman"

    url "https://raw.githubusercontent.com/fisherman/fisherman/2.10.0/fisher.fish"
    sha256 "a5f982ac0ade82c88a8a4da0b014a33266492f95a9156022534b6a1f8d7dd0b3"

    head "https://github.com/fisherman/fisherman.git"

    depends_on "fish"

    def install

        (share/"fish/vendor_functions.d/").install "fisher.fish"
        File.write("fisher-completion.fish", "fisher --complete")
        fish_completion.install "fisher-completion.fish" => "fisher.fish"
      ohai "You may need to restart any open terminal sessions for changes to take effect."

    end
end
```

**Comment by gyakovlev** [comment]
closing with fisherman/homebrew-tap/pull/2
